Add a function to build images immediately
modal-labs/modal-client pull request #2347
Opened 2024-10-16 19:52 UTC by pawalt

## Describe your changes

Resolves MOD-4102

<details> <summary>Backward/forward compatibility checks</summary>

---

Check these boxes or delete any item (or this section) if not relevant for this PR.

- [x] Client+Server: this change is compatible with old servers
- [x] Client forward compatibility: this change ensures client can accept data intended for later versions of itself

Note on protobuf: protobuf message changes in one place may have impact to
multiple entities (client, server, worker, database). See points above.

---

</details>

## Changelog

Images can now be built directly with `Image.build`.

2024-10-16 21:24 UTC, mwaskom commented on modal/image.py
> +        client = client or app._client or await _Client.from_env()
Do we need `app` as an argument here? Feels confusing to have an object that is usually passed to `App` have a method that accepts an `App` as an argument.

2024-10-16 21:24 UTC, mwaskom commented on modal/image.py
> +        """Build the image immediately rather than waiting for it to be used."""
Nit but the "waiting for it to be used" here is arguably not a correct description of what usually happens — images get build when we create apps or functions that _will_ use them.

2024-10-17 03:20 UTC, erikbern commented
I think `image.resolve()` might already do this, but could be wrong! Either way this I think this points to some complexity around managing "lazy" vs "eager" objects (c.f. `from_name` vs `lookup`)

2024-10-17 12:56 UTC, mwaskom requested changes
Discussed with Peyton on Slack but I don't think this actually solves the user's problem — not sure we should expand API without a clear rationale.

2024-10-21 18:04 UTC, pawalt commented
Cancelling as we have better ways to solve this UX pain

2024-10-21 18:04 UTC, closed without merging